# Append()

Name = ['Kiran','Komal','Sejal','Janvi','Siddhi'] 
Name.append('Ankita')
print(Name)

print('=======================================================')

# Extend()

Name = ['Kiran','Komal','Sejal','Janvi','Siddhi'] 
Name2 = ['Akshay','Sagar','Sumit','Gaurav','swayam']
Name.extend(Name2)
print(Name)

print('====================================================')

# Insert()

Name = ['Kiran','Komal','Sejal','Janvi','Siddhi'] 
Name.insert(0,'Ankita')
print(Name)

print('===============================================')

# Remove

Name = ['Vedant','Kiran','Komal','Sejal','Janvi','Siddhi'] 
Name.remove('Vedant')
print(Name)

print('=================================================')

# Reverse

Name = ['Ankita','Kiran','Komal','Sejal','Janvi','Siddhi'] 
Name.reverse()
print(Name)

print('========================================================')

# Cout